@JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNsaWVudDFAZ21haWwuY29tIiwiaWF0IjoxNjczODg0NDU5fQ.nTuyU32ge_XYZvgBHCT-OjkcoUgx3ZWkc_UVmzQFjR4

GET http://localhost:3001/login?user=123

###
GET http://localhost:3001/hotel_infos

###
GET http://localhost:3001/users

###
GET http://localhost:3001/user/1

###
GET http://localhost:3001/

###
GET http://localhost:3001/helloworld

###
GET http://localhost:3001/dashboard

###
GET http://localhost:3001/logout

###
POST http://localhost:3001/signup
Content-Type: application/json

{
  "email": "321@321.com.com",
  "name":"helloworld name",
  "password":"Aa1234567!"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
  "email": "client1@gmail.com",
  "password":"Aa1234567"
}

###
POST http://localhost:3001/login
Content-Type: application/json

{
  "email": "123@123.com",
  "password":"Aa1234567!"
}
